### PR TITLE
readme: remove dupe argument

### PR DESCRIPTION
**Pull request by mathiask88**
Did this on mobile.  Hope this works :)

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Mind updating `help.txt` as well? Also needs rebase for tests to pass :)

**Comment by ralphtheninja** [comment]
Nevermind, I can fix that myself :)

**Comment by ralphtheninja** [comment]
Done [here](https://github.com/mafintosh/prebuild-install/commit/786e56a8f568c6c64dfb4a797775126104640e17)

**Comment by mathiask88** [comment]
Nice,  thanks!

**Comment by ralphtheninja** [comment]
1.0.0

**Pull request merged**
