### PR TITLE
tweak installation messages

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by mathiask88** [comment]
Can we rephrase `installing inside prebuild-install directory, skipping download.` as well? Something like `installing as non-dependency, skipping download`?

**Comment by ralphtheninja** [comment]
> Can we rephrase installing inside prebuild-install directory, skipping download. as well? Something like installing as non-dependency, skipping download?

Of course!

**Comment by ralphtheninja** [comment]
@mathiask88 How about `installing standalone, skipping download` instead?

**Comment by mathiask88** [comment]
@ralphtheninja Yeah sure! 👍

**Comment by ralphtheninja** [comment]
Amended.

**Comment by mathiask88** [comment]
LGTM

**Pull request merged**
