### PR TITLE
bail out on download for git and dev installations

### PR DESCRIPTION
**Pull request by mathiask88**
#8 

/cc @ralphtheninja

### CODE REVIEW

**Comment by ralphtheninja** [comment]
+1

**Comment by juliangruber** [comment]
would an exit code of `0` be easier to integrate?

**Comment by ralphtheninja** [comment]
New minor I guess?

**Comment by mathiask88** [comment]
https://github.com/mafintosh/prebuild-install/issues/8#issuecomment-222384635 I'm +0 for this.  If you want it,  then just merge :) Minor should be good

**Comment by ralphtheninja** [comment]
1.1.0

**Pull request merged**
