### PR TITLE
prevent checking of the binary module, if platforms aren't same

### PR DESCRIPTION
**Pull request by akaJes**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Makes sense. But when does this happen? Just curious.

**Comment by akaJes** [comment]
Crossplatform issue https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/1180#issuecomment-320927570

**Comment by mathiask88** [comment]
Lets get this in.. @ralphtheninja do you release a new version with this? I have no npm rights :)

**Comment by ralphtheninja** [comment]
2.2.2

**Pull request merged**
