### PR TITLE
Closes vulnerabnility in tunnel-agent

### PR DESCRIPTION
**Pull request by designfrontier**
vulnerability details:
https://snyk.io/vuln/npm:tunnel-agent:20170305

Closed by upgrading to latest version of tunnel-agent

### CODE REVIEW

**Comment by mathiask88** [comment]
The caret should do the work, shouldn't it? But I don't mind to explicitly set that version. Other thoughts?

**Comment by designfrontier** [comment]
in this case no @mathiask88 

The carat will only match patch level because of the trailing 0. Carat is one of the more confusing parts of semver. Plus you want to exclude vulnerable versions (anything below 0.6.0).

**Comment by mathiask88** [comment]
@designfrontier Oh yes, your right. Then I am +1 for this. I checked the other `^0.x.x` dependencies and they are all fine.

/cc @ralphtheninja @juliangruber

**Comment by ralphtheninja** [comment]
@designfrontier Thanks!

**Comment by ralphtheninja** [comment]
merge

The history looks a bit odd because last time I published `2.1.2` I forgot to update upstream master branch. Sorry about this. Anyway, released this as a new minor because of bf033af

**Comment by designfrontier** [comment]
Thanks y'all!

**Pull request merged**
